server:
  port: 8083
  servlet:
    context-path: /api

spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: "postgres"
    password: "postgres"


logging:
  level:
    org.springframework.web: Debug